apiVersion: v1
kind: Template
objects:

##################
## ImageStreams ##
##################
- kind: ImageStream #database
  apiVersion: image.openshift.io/v1  
  metadata:
    name: ${REPO_NAME}-${GIT_BRANCH}-${COMMIT_ID}

###################
## Build Configs ##
###################
- kind: BuildConfig #database
  apiVersion: build.openshift.io/v1
  metadata:
    name: ${REPO_NAME}-${GIT_BRANCH}-${COMMIT_ID}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: '${REPO_NAME}-${GIT_BRANCH}-${COMMIT_ID}:latest'
    resources: {}
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 5
    strategy:
      type: Docker
      dockerStrategy: {}
    postCommit: {}
    source:
      type: Dockerfile
      git:
        uri: ${GITURL}
        ref: ${COMMIT_ID}

###################
## Parameters    ##
###################
parameters:
- name: GITURL
- name: REPO_NAME
- name: GIT_BRANCH
- name: COMMIT_ID
